color0 #44474e
color1 #ffb4ab
color2 #afc7f8
color3 #bec6dc
color4 #e7b7e7
color5 #afc7f8
color6 #bec6dc
color7 #e3e2e6
color8 #8e9099
color9 #ffb4ab
color10 #afc7f8
color11 #bec6dc
color12 #e7b7e7
color13 #afc7f8
color14 #bec6dc
color15 #e3e2e6

cursor                #e3e2e6
cursor_text_color     #000000
background            #000000
foreground            #e3e2e6
selection_foreground  #c4c6d0
selection_background  #44474e
active_border_color   #afc7f8
inactive_border_color #373a40
url_color             #afc7f8

active_tab_foreground   #163058
active_tab_background   #afc7f8
inactive_tab_foreground #c4c6d0
inactive_tab_background #373a40
cursor_trail_color      #c4c6d0
