-- Generated by nwg-displays on 2026-09-28 at 15:19:15. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 0.9999999999999999,
    vrr = 0
})
